Document: myget
Title: Debian myget Manual
Author: <insert document author here>
Abstract: This manual describes what myget is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/myget/myget.sgml.gz

Format: postscript
Files: /usr/share/doc/myget/myget.ps.gz

Format: text
Files: /usr/share/doc/myget/myget.text.gz

Format: HTML
Index: /usr/share/doc/myget/html/index.html
Files: /usr/share/doc/myget/html/*.html
